#In dieser Datei werden die Bilder aus dem "pics" Ordner als Variablen festgelegt, um sie später in das Spile einzufügen

playerPicture = r'.\pics\characterfront2.png'
characterPicture = r'.\pics\characterfront2.png'
studentPicture = r'.\pics\student.png'
teacherPicture = r'.\pics\teacher.png'
principlePicture = r'.\pics\principle.png'
testPicture = r'.\pics\test.png'
examPicture = r'.\pics\exam.png'
finalsPicture = r'.\pics\finals.png'

room1Picture = r'.\pics\room1.png'
room2Picture = r'.\pics\room2.png'
room3Picture = r'.\pics\room3.png'
room4Picture = r'.\pics\room4.png'
room5Picture = r'.\pics\room5.png'
room6Picture = r'.\pics\room6.png'
room7Picture = r'.\pics\room7.png'
room8Picture = r'.\pics\room8.png'
room9Picture = r'.\pics\room9.png'